######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/logo.svg"
logo_on_black: "/img/logo.svg"
custom_css: ["/css/style.css"]
custom_js: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: []

github:
  repo_url: "https://github.com/betterbytes-org/www/blob/master"
  show_edit_link: false

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/betterbytes-org"
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/company/tock-foundation"
  mastodon: "https://fosstodon.org/@tock"
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
