baseURL = 'https://betterbytes.org/'
languageCode = 'en-us'
title = 'Better Bytes'
[menus]
  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 1
  [[menus.main]]
    name = "Goals"
    pageRef = "/goals"
    weight = 2
  [[menus.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 3
  [[menus.main]]
    name = "Get Involved"
    pageRef = "/get-involved"
    weight = 4
